blender_path: "/Applications/Blender.app/Contents/MacOS/Blender"
seed: 1912
render:
  nb_frames: 200 
  resolution: 1024
  camera:
    elevation: [45,90]
    theta: 360
    nb_anchors: 10
    distance_center: 1
content:
  nb_poses: 4
  urdf_content_path: "/Users/jtremblay/code/blender_robot_animation/models/baxter_common/baxter_description/"
  urdf_path: "urdf/baxter.urdf"
  hdri_env_map: "/Users/jtremblay/code/blender_robot_animation/models/hdris/"
  materials_path: "/Users/jtremblay/code/holodeck_blender/assets/textures/"
  random_material: True
output_path: "/Users/jtremblay/code/blender_robot_animation/renders/baxter/"
