base: configs/base.yaml
seed: 2223675
render:
  nb_frames: 600 
  resolution: 1024
  camera:
    distance_center: 1.85
content:
  urdf_content_path: ${base.base_path}/models/icub-models/iCub/robots/
  urdf_path: iCubParis02/model.urdf
  hdri_env_map: ${base.base_path}/models/hdris/
  materials_path: /Users/jtremblay/code/holodeck_blender/assets/textures/
output_path: ${base.base_path}/renders/icub/
nb_bullet_steps: 10
random_materials: False
offset: [0,0,0]
amplitude_camera: 0.4
prob_change_pose: 0.1
step_size: 0.04
rot_x: -1.5708
# test
test_scene: True
test_every_frame: 10
nb_cameras: 6
ignore_list: [1,2,12,13]