base: configs/base.yaml
seed: 190191
render:
  nb_frames: 600 
  resolution: 1024
  camera:
    distance_center: 2.8
content:
  urdf_content_path: ${base.base_path}/models/differentiable-robot-model/diff_robot_data/kinova_description/
  urdf_path: urdf/jaco_clean.urdf
  hdri_env_map: ${base.base_path}/models/hdris/
  materials_path: /Users/jtremblay/code/holodeck_blender/assets/textures/
output_path: ${base.base_path}/renders/jaco/
nb_bullet_steps: 10
random_materials: True
offset: [0,0,.35]
amplitude_camera: 0.3
prob_change_pose: 0.1
step_size: 0.01
rot_x: 0
# test
test_scene: True
test_every_frame: 10
nb_cameras: 6
ignore_list: []