blender_path: "/Applications/Blender.app/Contents/MacOS/Blender"
seed: 1901912
render:
  nb_frames: 100 
  resolution: 1024
  camera:
    elevation: [45,90]
    theta: 180
    nb_anchors: 10
    distance_center: 4
content:
  nb_poses: 4
  urdf_content_path: "/Users/jtremblay/code/blender_robot_animation/models/differentiable-robot-model/diff_robot_data/panda_description/"
  urdf_path: "urdf/panda.urdf"
  hdri_env_map: "/Users/jtremblay/code/blender_robot_animation/models/hdris/"
  materials_path: "/Users/jtremblay/code/holodeck_blender/assets/textures/"
  random_material: True
output_path: "/Users/jtremblay/code/blender_robot_animation/renders/panda/"
nb_bullet_steps: 10
