base: configs/base.yaml
seed: 1901912
render:
  nb_frames: 100 
  resolution: 1024
  camera:
    distance_center: 4
content:
  nb_poses: 4
  urdf_content_path: "${base.base_path}/models/differentiable-robot-model/diff_robot_data/panda_description/"
  urdf_path: "urdf/panda.urdf"
  hdri_env_map: "${base.base_path}/models/hdris/"
  materials_path: "/Users/jtremblay/code/holodeck_blender/assets/textures/"
  random_material: True
output_path: "${base.base_path}/renders/panda/"
nb_bullet_steps: 10
random_materials: True
offset: [0,0,0]
amplitude_camera: 0.3
prob_change_pose: 0.1
step_size: 0.05
rot_x: 0
